/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin-dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedDailySummaryRouteImport } from './routes/_authenticated/daily-summary'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnquiriesRouteImport } from './routes/_authenticated/enquiries'
import { Route as AuthenticatedFarmerDashboardRouteImport } from './routes/_authenticated/farmer-dashboard'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated/farmers'
import { Route as AuthenticatedLipaPolePoleRouteImport } from './routes/_authenticated/lipa-pole-pole'
import { Route as AuthenticatedMilkPricesRouteImport } from './routes/_authenticated/milk-prices'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReceiveMilkRouteImport } from './routes/_authenticated/receive-milk'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin-dashboard',
    path: '/admin-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailySummaryRoute =
  AuthenticatedDailySummaryRouteImport.update({
    id: '/daily-summary',
    path: '/daily-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquiriesRoute = AuthenticatedEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmerDashboardRoute =
  AuthenticatedFarmerDashboardRouteImport.update({
    id: '/farmer-dashboard',
    path: '/farmer-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLipaPolePoleRoute =
  AuthenticatedLipaPolePoleRouteImport.update({
    id: '/lipa-pole-pole',
    path: '/lipa-pole-pole',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMilkPricesRoute = AuthenticatedMilkPricesRouteImport.update({
  id: '/milk-prices',
  path: '/milk-prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiveMilkRoute =
  AuthenticatedReceiveMilkRouteImport.update({
    id: '/receive-milk',
    path: '/receive-milk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/daily-summary': typeof AuthenticatedDailySummaryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/farmer-dashboard': typeof AuthenticatedFarmerDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/lipa-pole-pole': typeof AuthenticatedLipaPolePoleRoute
  '/milk-prices': typeof AuthenticatedMilkPricesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/receive-milk': typeof AuthenticatedReceiveMilkRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/daily-summary': typeof AuthenticatedDailySummaryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/farmer-dashboard': typeof AuthenticatedFarmerDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/lipa-pole-pole': typeof AuthenticatedLipaPolePoleRoute
  '/milk-prices': typeof AuthenticatedMilkPricesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/receive-milk': typeof AuthenticatedReceiveMilkRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/daily-summary': typeof AuthenticatedDailySummaryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enquiries': typeof AuthenticatedEnquiriesRoute
  '/_authenticated/farmer-dashboard': typeof AuthenticatedFarmerDashboardRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRoute
  '/_authenticated/lipa-pole-pole': typeof AuthenticatedLipaPolePoleRoute
  '/_authenticated/milk-prices': typeof AuthenticatedMilkPricesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/receive-milk': typeof AuthenticatedReceiveMilkRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin-dashboard'
    | '/change-password'
    | '/collections'
    | '/daily-summary'
    | '/dashboard'
    | '/enquiries'
    | '/farmer-dashboard'
    | '/farmers'
    | '/lipa-pole-pole'
    | '/milk-prices'
    | '/notifications'
    | '/payments'
    | '/receive-milk'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin-dashboard'
    | '/change-password'
    | '/collections'
    | '/daily-summary'
    | '/dashboard'
    | '/enquiries'
    | '/farmer-dashboard'
    | '/farmers'
    | '/lipa-pole-pole'
    | '/milk-prices'
    | '/notifications'
    | '/payments'
    | '/receive-milk'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin-dashboard'
    | '/_authenticated/change-password'
    | '/_authenticated/collections'
    | '/_authenticated/daily-summary'
    | '/_authenticated/dashboard'
    | '/_authenticated/enquiries'
    | '/_authenticated/farmer-dashboard'
    | '/_authenticated/farmers'
    | '/_authenticated/lipa-pole-pole'
    | '/_authenticated/milk-prices'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/receive-milk'
    | '/_authenticated/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-dashboard': {
      id: '/_authenticated/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-summary': {
      id: '/_authenticated/daily-summary'
      path: '/daily-summary'
      fullPath: '/daily-summary'
      preLoaderRoute: typeof AuthenticatedDailySummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries': {
      id: '/_authenticated/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AuthenticatedEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer-dashboard': {
      id: '/_authenticated/farmer-dashboard'
      path: '/farmer-dashboard'
      fullPath: '/farmer-dashboard'
      preLoaderRoute: typeof AuthenticatedFarmerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lipa-pole-pole': {
      id: '/_authenticated/lipa-pole-pole'
      path: '/lipa-pole-pole'
      fullPath: '/lipa-pole-pole'
      preLoaderRoute: typeof AuthenticatedLipaPolePoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milk-prices': {
      id: '/_authenticated/milk-prices'
      path: '/milk-prices'
      fullPath: '/milk-prices'
      preLoaderRoute: typeof AuthenticatedMilkPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receive-milk': {
      id: '/_authenticated/receive-milk'
      path: '/receive-milk'
      fullPath: '/receive-milk'
      preLoaderRoute: typeof AuthenticatedReceiveMilkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDailySummaryRoute: typeof AuthenticatedDailySummaryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnquiriesRoute: typeof AuthenticatedEnquiriesRoute
  AuthenticatedFarmerDashboardRoute: typeof AuthenticatedFarmerDashboardRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRoute
  AuthenticatedLipaPolePoleRoute: typeof AuthenticatedLipaPolePoleRoute
  AuthenticatedMilkPricesRoute: typeof AuthenticatedMilkPricesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReceiveMilkRoute: typeof AuthenticatedReceiveMilkRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDailySummaryRoute: AuthenticatedDailySummaryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnquiriesRoute: AuthenticatedEnquiriesRoute,
  AuthenticatedFarmerDashboardRoute: AuthenticatedFarmerDashboardRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRoute,
  AuthenticatedLipaPolePoleRoute: AuthenticatedLipaPolePoleRoute,
  AuthenticatedMilkPricesRoute: AuthenticatedMilkPricesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReceiveMilkRoute: AuthenticatedReceiveMilkRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
