name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          # Find the directory containing gradlew using a wildcard path
          APP_DIR=$(dirname $(find . -name "gradlew" -type f -print -quit))
          echo "Target project directory: $APP_DIR"
          cd "$APP_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maziwaflow-debug-apk
          path: '**/app/build/outputs/apk/debug/*.apk'
